/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * Auditorias.java
 *
 * Created on 03-abr-2013, 0:03:34
 */

package sistema;

import Clases.ConexionMySQL;
import Clases.Forms;
import javax.swing.table.DefaultTableModel;
import java.sql.*;
import javax.swing.JOptionPane;
import javax.swing.table.TableColumn;

/**
 *
 * @author Administrador
 */
public class Auditorias extends javax.swing.JInternalFrame {
    //Modelo de la Tabla
    //******************
    DefaultTableModel MODELO;

    /** Creates new form Auditorias */
    public Auditorias() {
        initComponents();
        //Cargar tabla
        //************
        this.CargarTabla();
        //tamaño de la tabla
        //******************
        this.TamañoTabla();
    }

    //Metodo para el Tamaño Tabla
    //***************************
    private void TamañoTabla(){
        TableColumn column = null;
        column = tblAuditoria.getColumnModel().getColumn(0);
        column.setPreferredWidth(100);
        column = tblAuditoria.getColumnModel().getColumn(1);
        column.setPreferredWidth(200);
        column = tblAuditoria.getColumnModel().getColumn(2);
        column.setPreferredWidth(200);
        column = tblAuditoria.getColumnModel().getColumn(3);
        column.setPreferredWidth(200);
        column = tblAuditoria.getColumnModel().getColumn(4);
        column.setPreferredWidth(200);
        column = tblAuditoria.getColumnModel().getColumn(5);
        column.setPreferredWidth(200);
        column = tblAuditoria.getColumnModel().getColumn(6);
        column.setPreferredWidth(380);
    }

    //Metodo para Cargar tabla
    //************************
    private void CargarTabla(){
        //Arreglo para los Titulos
        //***********************
        String [] titulos = {"Codigo", "Usuario", "Nombre","Apellido", "Fecha", "Hora", "Modulo"};
        //Arreglo para los Registro
        //************************
        String [] registros = new String [7];
        //Creamos el Modelo de la Tabla
        //*****************************
        MODELO = new DefaultTableModel(null, titulos);
        //Creamos Conexion
        //****************
        ConexionMySQL mysql = new ConexionMySQL();
        Connection cn = mysql.Conectar();
        //Creamos Sentencia SQL
        //*********************
        String SQL = "";
        SQL += "SELECT a.id, u.usuario, u.nombres, u.apellidos, a.fecha, a.hora, m.denominacion ";
        SQL += "from auditoria as a, usuarios as u, modulos as m ";
        SQL += "where a.user = u.cedula and a.modulo = m.id ";
        //Ejecutamos Accion
        //*****************
        try{
            Statement st = cn.createStatement();
            ResultSet rs = st.executeQuery(SQL);
            while(rs.next()){
                registros[0] = rs.getString(1);
                registros[1] = rs.getString(2);
                registros[2] = rs.getString(3);
                registros[3] = rs.getString(4);
                registros[4] = rs.getString(5);
                registros[5] = rs.getString(6);
                registros[6] = rs.getString(7);
                MODELO.addRow(registros);
            }
            tblAuditoria.setModel(MODELO);
        }
        catch(SQLException ex){
            JOptionPane.showMessageDialog(null, ex);
        }
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblAuditoria = new javax.swing.JTable();

        setClosable(true);
        setIconifiable(true);
        setTitle("Entrada a los Modulos del Sistema");
        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                formComponentShown(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 12));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Auditoria del Sistema");

        tblAuditoria.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        tblAuditoria.setEnabled(false);
        jScrollPane1.setViewportView(tblAuditoria);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 836, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 836, Short.MAX_VALUE))
                .addGap(21, 21, 21))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 395, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(34, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentShown
        //Centramos Formulario
        //********************
        Forms f = new Forms(this);
        f.setCenterFrame();
    }//GEN-LAST:event_formComponentShown


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblAuditoria;
    // End of variables declaration//GEN-END:variables

}
