/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * Listado_Clientes.java
 *
 * Created on 16-nov-2013, 14:24:13
 */

package sistema;

import Clases.Alumnos;
import Clases.BDAlumnos;
import Clases.ConexionMySQL;
import Clases.Forms;
import java.sql.*;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableColumn;

/**
 *
 * @author Administrador
 */
public class Buscar_Alumno extends javax.swing.JInternalFrame {
    //Variables
    //*********
    String ID_ACT;
    //Modelo de la Tabla
    //******************
    DefaultTableModel MODELO;


    /** Creates new form Listado_Clientes */
    public Buscar_Alumno() {
        initComponents();
        //Titulo del Formulario
        //*********************
        this.setTitle("Buscar Alumno");
        //Carrgar Tabla
        //*************
        this.CargarTabla("");
        //Tamaño de la Tabla
        //******************
        this.TamañoTabla();
    }

         //Metodo para el Tamaño Tabla
    //***************************
    private void TamañoTabla(){
        TableColumn column = null;
        column = this.tblClientes.getColumnModel().getColumn(0);
        column.setPreferredWidth(150);
        column = this.tblClientes.getColumnModel().getColumn(1);
        column.setPreferredWidth(200);
        column = this.tblClientes.getColumnModel().getColumn(2);
        column.setPreferredWidth(200);
    }

    //Metodo para Cargar Tabla
    //************************
    private void CargarTabla(String Valor){
        //Arreglo para los Titulos
        //************************
        String [] titulos = {"Cedula", "Nombres", "Apellidos"};
        //Arreglo para los Registro
        //*************************
        String [] registros = new String [3];
        //Creamos el modelo de la Tabla
        //*****************************
        MODELO = new DefaultTableModel(null, titulos);
        //Creamos la Conexion
        //*******************
        ConexionMySQL mysql = new ConexionMySQL();
        Connection cn = mysql.Conectar();
        //Creamos Sentencia SQL
        //*********************
        String SQL = "";
        SQL += "SELECT * ";
        SQL += "FROM alumnos ";
        SQL += "WHERE nombres LIKE '%"+Valor+"%'";
        //Ejecutacmos Sentencia SQL
        //*************************
        try {
            Statement st = cn.createStatement();
            ResultSet rs = st.executeQuery(SQL);
            while (rs.next()){
                registros[0] = rs.getString(1);
                registros[1] = rs.getString(2);
                registros[2] = rs.getString(3);
                MODELO.addRow(registros);
            }
            this.tblClientes.setModel(MODELO);
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(this, ex);
        }
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblClientes = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtbuscar = new javax.swing.JTextField();
        btnSalir = new javax.swing.JButton();

        setTitle("Alumnos Registrados");
        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                formComponentShown(evt);
            }
        });

        tblClientes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        tblClientes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblClientesMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblClientes);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Buscar Alumno"));

        jLabel1.setText("Buscar Alumno:");

        txtbuscar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtbuscarKeyReleased(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtbuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 446, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(131, 131, 131))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtbuscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        btnSalir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sistema/iconos/application-exit-3.png"))); // NOI18N
        btnSalir.setText("Cerrar");
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 558, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 256, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(15, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tblClientesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblClientesMouseClicked
        long codigo=Long.parseLong(String.valueOf(tblClientes.getModel().getValueAt(tblClientes.getSelectedRow(), 0)));
        try {
            Alumnos c=BDAlumnos.buscarCodigo(codigo);
            Inscripciones.txtAlumno.setText(String.valueOf(c.getnombres()));
            Inscripciones.txtCedula.setText(String.valueOf(c.getcedula()));
            Inscripciones.CEDULA1= Inscripciones.txtCedula.getText();
            this.dispose();
        } catch (SQLException ex) {
            System.out.println("Error Al Seleccionar Elemento:" + ex.getMessage());
        }
}//GEN-LAST:event_tblClientesMouseClicked

    private void formComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentShown
        //Centrar Formulario
        //******************
        Forms f = new Forms(this);
        f.setCenterFrame();
    }//GEN-LAST:event_formComponentShown

    private void txtbuscarKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtbuscarKeyReleased
        //Capturamos el valor del campo
        //*****************************
        String valor = this.txtbuscar.getText();
        //Cargamos la Tabla segun el valor
        //********************************
        this.CargarTabla(valor);
        //Colocamos tamaño a la tabla
        //***************************
        this.TamañoTabla();
    }//GEN-LAST:event_txtbuscarKeyReleased

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnSalirActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSalir;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblClientes;
    private javax.swing.JTextField txtbuscar;
    // End of variables declaration//GEN-END:variables

}
